agentName:BfdMon-%sliceId

Include: EosSdk_agent.include
Include: EosSdk_eth_intf.include
Include: EosSdk_eth_lag_intf.include
Include: EosSdk_eth_phy_intf.include
Include: EosSdk_fib.include
Include: EosSdk_intf.include
Include: EosSdk_IntfMgrHelper.include
Include: EosSdk_ip_intf.include
Include: EosSdk_ip_route.include
Include: EosSdk_lldp.include
Include: EosSdk_subintf.include
Include: EosSdk_system.include
Include: EosSdk_vrf.include
Include: EosSdk_bfd_session.include